### ISSUE TITLE
CSS Custom Properties for base and blend

### ISSUE THREAD

**Issue by julzmon** [jonathantneal/postcss-color-mod-function#18]
Is it possible to use custom properties for both of the colors values?
 e.g. `color-mod(var(--color-gray-900) blend(var(--color-gray-900) 10%))`

**Comment by jonathantneal** [comment]
It should work, but I verified it does not, because there is an issue with the walker that ships with the value parser this plugin uses. In the next release, I will use my own walker that does not suffer this same defect.
