### ISSUE TITLE
Doesn't work with HEX colors

### ISSUE THREAD

**Issue by evgeny-petukhov** [jonathantneal/postcss-color-mod-function#8]
When using hex color (`color-mod(#000000 b(50%))`) it returns `rgb(NaN, NaN, NaN)`

**Comment by jonathantneal** [comment]
Resolved by https://github.com/jonathantneal/postcss-color-mod-function/commit/4ab54f63231e06bf934d5b97a626785c1344d7f9

Published in 2.4.2

**Comment by jonathantneal** [comment]
Thanks for reporting this, @evgeny-petukhov :)

**Comment by evgeny-petukhov** [comment]
Thanks for quick fix 👍
